// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfoxyAA6TNB3dtaF7HcuQDA9rewLY-WZc',
    appId: '1:250142855053:web:a7e40cf107617ded34f7c4',
    messagingSenderId: '250142855053',
    projectId: 'valuables-79a68',
    authDomain: 'valuables-79a68.firebaseapp.com',
    storageBucket: 'valuables-79a68.firebasestorage.app',
    measurementId: 'G-B1PBYZY66C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa8tDGh2F88DijgUBnRA5_KRuxaLaBMh4',
    appId: '1:250142855053:android:291407e4299d632434f7c4',
    messagingSenderId: '250142855053',
    projectId: 'valuables-79a68',
    storageBucket: 'valuables-79a68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkcJT6LVExQgGsUooM7k-fHWadZHnUBqA',
    appId: '1:250142855053:ios:c64ea532b822db9f34f7c4',
    messagingSenderId: '250142855053',
    projectId: 'valuables-79a68',
    storageBucket: 'valuables-79a68.firebasestorage.app',
    iosBundleId: 'com.example.valuables',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkcJT6LVExQgGsUooM7k-fHWadZHnUBqA',
    appId: '1:250142855053:ios:c64ea532b822db9f34f7c4',
    messagingSenderId: '250142855053',
    projectId: 'valuables-79a68',
    storageBucket: 'valuables-79a68.firebasestorage.app',
    iosBundleId: 'com.example.valuables',
  );
}
